### ISSUE TITLE
refactor: use StringBuilder

### ISSUE THREAD

**Issue by InRedikaWB** [InRedikaWB/Fluda#26]
**Describe the solution you'd like**
Для генерации SQL-кода используется не оптимальный алгоритм - обычный конкат строк. Нужно переписать на StringBuilder

**Comment by hrrrrustic** [comment]
Сильно

**Comment by InRedikaWB** [comment]
После небольшого ресерча стало ясно, что профита будет не много т.к. использовался string.Join, который и так под коробкой юзать стринг билдер.
Но в любом случае fixed 7de0952a20bfa57f8eb4a71eca4f87022ef97d1b
