### ISSUE TITLE
[feat] EnumResolvers

### ISSUE THREAD

**Issue by hrrrrustic** [InRedikaWB/Fluda#49]
Пачку копипасту резолверов вроде вычистили, но вот тут есть копипаст создания
https://github.com/InRedikaWB/Fluda/blob/master/Fluda/Abstractions/Contracts/ContractFieldProvider.cs#L38
Явно можно все это снести, но референсов на методы сейчас нет, так что сам трогать не стал

**Comment by InRedikaWB** [comment]
Снеси как?  Эти методы инкапсулирют логику создание филдов.

> так что сам трогать не стал
Можно было кинуть пулреквест, чтобы было понимание, что ты хочешь сделать.

**Comment by InRedikaWB** [comment]
@hrrrrustic закрываю ишую?

**Comment by hrrrrustic** [comment]
Да
