### ISSUE TITLE
Find/Delete

### ISSUE THREAD

**Issue by hrrrrustic** [InRedikaWB/Fluda#78]
В апдейте используется сущность, поэтому там нужно делать обращение к ней, в Find/Delete это не нужно, но точка все равно будет
https://github.com/InRedikaWB/Fluda/blob/dev/Fluda.CodeGeneration/Generators/SharpTypes/TableDbScopeGenerator.cs#L261

**Comment by InRedikaWB** [comment]
Fix: 6a690d2e8bc575d8dca3914e5ec3ea3c65296beb
